name: Automated Instagram Poster
on:
  workflow_dispatch:
  schedule:
    - cron: '0 01 * * *'  # 6:00 PM PDT (01:00 UTC next day)

jobs:
  post-instagram:
    runs-on: ubuntu-latest
    env:
      INSTA: ${{ secrets.INSTA }}
      OPENAI: ${{ secrets.OPENAI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE/Automated_AI_Instagram:$PYTHONPATH" >> $GITHUB_ENV
      - name: Install dependencies
        run: pip install -r Automated_AI_Instagram/requirements.txt
      - name: Run Insta Poster
        run: python -m Automated_AI_Instagram.src.main
